version: '3.4'

services:
  webapp:
    image: aws-test-image
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - DOTNET_EnableDiagnostics=0
      - ASPNETCORE_URLS=http://+:80
